### ISSUE TITLE
api instrumentation for general functions which does not have callbacks

### ISSUE THREAD

**Issue by ajcs3** [Dynatrace/nodejs-agent-api#3]
Thanks for the documentation for async with call backs. But how could this be used in case of general functions for example if we have some background jobs which polls DB and does some processing which doesn't have a callback.
Any examples would help.

**Comment by danielkhan** [comment]
As mentioned, please only use this module if you are seeing context loss problems.
Your case should be fully covered by the agent out-of-the box.
